version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CONNECTION_URL=mongodb://mongo:27017/test
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "8088:80"

  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"

